#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

node ./scripts/update-vivakits-version.js

if git diff --cached --quiet; then
  echo "No changes to commit."
else
  git add .
  git commit -m "Vivakits version updated"
  echo "Changes committed with 'Vivakits version updated'."
fi
